/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/pets/{id}": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional tenant identifier for data isolation. When provided, all operations will be scoped to this tenant, ensuring data separation between different organizations or users. If omitted, operations will access the shared/public data pool where data may be visible to and modified by other users. */
                "X-Tenant-ID"?: components["parameters"]["TenantID"];
            };
            path: {
                /**
                 * @description Unique identifier for the pet
                 * @example 01936c8f-1234-7000-8000-111111111111
                 */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get Pet
         * @description Retrieve detailed information about a specific pet.
         */
        get: operations["getPet"];
        /**
         * Update Pet
         * @description Update information for an existing pet. Staff only.
         */
        put: operations["updatePet"];
        post?: never;
        /**
         * Delete Pet
         * @description Delete a pet from the system. Staff only.
         */
        delete: operations["deletePet"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional tenant identifier for data isolation. When provided, all operations will be scoped to this tenant, ensuring data separation between different organizations or users. If omitted, operations will access the shared/public data pool where data may be visible to and modified by other users. */
                "X-Tenant-ID"?: components["parameters"]["TenantID"];
            };
            path?: never;
            cookie?: never;
        };
        /**
         * List Pets
         * @description Retrieve a paginated list of pets available for adoption with optional filtering.
         */
        get: operations["listPets"];
        put?: never;
        /**
         * Create Pet
         * @description Add a new pet to the store catalog, making it available for adoption.
         *
         *     ## Pet Lifecycle Workflow
         *
         *     When a new pet enters the system:
         *
         *     1. **Intake**: Staff creates a pet record with this endpoint (status: `available`)
         *     2. **Profile**: Pet details include species, breed, age, medical info, photos, and adoption fee
         *     3. **Discovery**: Pet appears in search results and listings
         *     4. **Adoption Application**: Potential adopters can apply through the adoption endpoints
         *     5. **Adoption**: Once approved, pet status changes to `adopted`
         *     6. **Post-Adoption**: Pet record is retained for historical purposes
         *
         *     **Access**: This operation requires staff permissions (`write:pets` scope or valid Bearer token). Only authenticated staff members can add pets to the system.
         */
        post: operations["createPet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Chat Completion
         * @description Creates a model response for a chat conversation with the Pet Adoption Advisor AI. Supports streaming responses using Server-Sent Events (SSE).
         *
         *     ## Pet Adoption Advisor
         *
         *     Our AI assistant helps users:
         *     - Get personalized pet recommendations
         *     - Learn about pet care and adoption process
         *     - Answer questions about specific pets
         *     - Provide breed information and compatibility advice
         *
         *     ## Streaming Mode
         *
         *     When `stream: true`, the response is sent as Server-Sent Events (SSE), with each token delivered incrementally. This provides a better user experience for longer responses.
         *
         *     ### Stream Format
         *
         *     Each chunk is sent as:
         *     ```
         *     data: {"id":"chatcmpl_abc","object":"chat.completion.chunk","choices":[{"delta":{"content":"Hello"},"index":0}]}
         *
         *     ```
         *
         *     The stream ends with:
         *     ```
         *     data: [DONE]
         *
         *     ```
         *
         *     ## Non-Streaming Mode
         *
         *     When `stream: false` or omitted, returns a complete response object.
         */
        post: operations["createChatCompletion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets/{id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Pet Image
         * @description Upload an image for the specified pet. Requires authentication and write:pets permission.
         */
        post: operations["uploadPetPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pay Order
         * @description Process payment for an existing order.
         *
         *     ## Payment Workflow
         *
         *     Payment processing follows this workflow:
         *
         *     1. **Create Order**: First create an order using `POST /orders` (status: `placed`)
         *     2. **Submit Payment**: Call this endpoint with payment details (card or bank account)
         *     3. **Payment Processing**: The payment is processed with status `processing`
         *     4. **Payment Result**:
         *        - **Success**: Payment status becomes `succeeded`, order status updates to `approved`
         *        - **Failure**: Payment status becomes `failed`, order remains `placed` and can be retried
         *     5. **Receipt**: After successful payment, retrieve the receipt from the order details
         *
         *     **Security Note**: Sensitive payment data (like CVC codes) are `writeOnly` and never returned in responses. Card numbers and account numbers are masked when read.
         */
        post: operations["createOrderPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Inventory
         * @description Returns a mapping of status codes to quantities.
         */
        get: operations["getInventory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional tenant identifier for data isolation. When provided, all operations will be scoped to this tenant, ensuring data separation between different organizations or users. If omitted, operations will access the shared/public data pool where data may be visible to and modified by other users. */
                "X-Tenant-ID"?: components["parameters"]["TenantID"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Order
         * @description Create a new order in the store.
         */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional tenant identifier for data isolation. When provided, all operations will be scoped to this tenant, ensuring data separation between different organizations or users. If omitted, operations will access the shared/public data pool where data may be visible to and modified by other users. */
                "X-Tenant-ID"?: components["parameters"]["TenantID"];
            };
            path: {
                /**
                 * @description Unique identifier for the order
                 * @example 019b4139-1234-7abc-8def-123456789abc
                 */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get Order
         * @description Retrieve order information by order ID.
         */
        get: operations["getOrder"];
        put?: never;
        /**
         * Callback Example
         * @description Handles order events and supports asynchronous processing with Callback.
         */
        post: operations["callbackOrder"];
        /**
         * Delete Order
         * @description Delete an existing order by its unique identifier.
         */
        delete: operations["deleteOrder"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional tenant identifier for data isolation. When provided, all operations will be scoped to this tenant, ensuring data separation between different organizations or users. If omitted, operations will access the shared/public data pool where data may be visible to and modified by other users. */
                "X-Tenant-ID"?: components["parameters"]["TenantID"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create User
         * @description Create a new user in the system.
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional tenant identifier for data isolation. When provided, all operations will be scoped to this tenant, ensuring data separation between different organizations or users. If omitted, operations will access the shared/public data pool where data may be visible to and modified by other users. */
                "X-Tenant-ID"?: components["parameters"]["TenantID"];
            };
            path: {
                /**
                 * @description Unique identifier for the user
                 * @example user_abc123xyz
                 */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get User
         * @description Retrieve user information by user ID.
         */
        get: operations["getUserById"];
        /**
         * Update User
         * @description Update user information. Only the logged-in user can perform this operation.
         */
        put: operations["updateUser"];
        post?: never;
        /**
         * Delete User
         * @description Delete a user account. Only the logged-in user can perform this operation.
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Token (Login)
         * @description Authenticate user and obtain an access token.
         */
        post: operations["createToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface webhooks {
    orderStatusChanged: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Order Status Changed Event
         * @description Triggered when an order's status changes. This webhook notifies your system of order lifecycle events, enabling real-time updates for order tracking, notifications, and fulfillment workflows.
         *
         *     ## Status Transitions
         *
         *     Orders follow this lifecycle:
         *     - `PLACED` → `APPROVED` (payment confirmed)
         *     - `APPROVED` → `SHIPPED` (order dispatched)
         *     - `SHIPPED` → `DELIVERED` (order completed)
         *     - Any status → `CANCELLED` (order cancelled)
         *
         *     ## Webhook Security
         *
         *     All webhooks include a signature header (`X-Webhook-Signature`) for verification. See our [webhook security guide](https://petstoreapi.com/docs/webhooks/security) for implementation details.
         */
        post: operations["orderStatusChangedWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    paymentSucceeded: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Payment Succeeded Event
         * @description Triggered when a payment is successfully processed and confirmed. This webhook notifies your system of successful payment transactions, enabling real-time updates for order fulfillment, customer notifications, and accounting workflows.
         *
         *     ## Payment Processing
         *
         *     When a payment succeeds:
         *     - Payment status changes to `SUCCEEDED`
         *     - Order status typically updates to `APPROVED`
         *     - Payment receipt is generated
         *     - Funds are confirmed and captured
         *
         *     ## Webhook Security
         *
         *     All webhooks include a signature header (`X-Webhook-Signature`) for verification. See our [webhook security guide](https://petstoreapi.com/docs/webhooks/security) for implementation details.
         */
        post: operations["paymentSucceededWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface components {
    schemas: {
        /** @description Animal information in the pet store available for adoption. */
        Pet: {
            /**
             * Format: uuid
             * @description Unique identifier for the pet (UUID v7)
             * @example 019b4132-70aa-764f-b315-e2803d882a24
             * @example 019b4127-54d5-76d9-b626-0d4c7bfce5b6
             */
            readonly id: string;
            /**
             * @description The species of the pet
             * @enum {string}
             */
            species: "DOG" | "CAT" | "RABBIT" | "BIRD" | "REPTILE" | "OTHER";
            /**
             * @description The pet's name
             * @example Whiskers
             * @example Max
             * @example Luna
             */
            name: string;
            /**
             * @description The breed of the pet
             * @example Domestic Shorthair
             * @example Labrador Retriever
             * @example Holland Lop
             */
            breed?: string;
            /**
             * @description Age of the pet in months
             * @example 18
             * @example 36
             * @example 6
             */
            ageMonths: number;
            /**
             * @description Size category of the pet
             * @enum {string}
             */
            size?: "SMALL" | "MEDIUM" | "LARGE";
            /**
             * @description Primary color or coloring pattern
             * @example Orange Tabby
             * @example Black
             * @example Brown and White
             */
            color?: string;
            /**
             * @description The pet's gender
             * @enum {string}
             */
            gender?: "MALE" | "FEMALE" | "UNKNOWN";
            /** @description Whether the pet is good with children */
            goodWithKids?: boolean;
            /**
             * @description Adoption fee amount
             * @example 75.00
             * @example 150.00
             * @example 50.00
             */
            price: string;
            /**
             * @description Currency code for the adoption fee (ISO 4217)
             * @default USD
             * @example USD
             * @example EUR
             * @example GBP
             */
            currency: string;
            /** @description Detailed description of the pet's personality and traits */
            description?: string;
            /**
             * @description Current adoption status
             * @enum {string}
             */
            status: "AVAILABLE" | "PENDING" | "ADOPTED" | "NOT_AVAILABLE";
            /**
             * Format: date-time
             * @description Timestamp when the pet record was created (RFC 3339)
             * @example 2025-12-21T13:56:23Z
             * @example 2025-11-15T08:30:00Z
             */
            readonly createdAt: string;
            /**
             * Format: date-time
             * @description Timestamp when the pet record was last updated (RFC 3339)
             * @example 2025-12-21T13:56:23Z
             * @example 2025-12-21T15:30:45Z
             */
            readonly updatedAt: string;
            /**
             * Format: uuid
             * @description Optional tenant identifier for data isolation. When present, indicates this pet belongs to a specific tenant. Null or omitted means the pet is in the shared/public data pool.
             * @example 550e8400-e29b-41d4-a716-446655440000
             * @example 7c9e6679-7425-40de-944b-e07fc1f90ae7
             */
            readonly tenantId?: string | null;
            /** @description URLs of pet photos */
            photos?: string[];
            medicalInfo?: {
                /** @description Whether the pet has been spayed or neutered */
                spayedNeutered?: boolean;
                /** @description Whether the pet is up to date on vaccinations */
                vaccinated?: boolean;
                /** @description Whether the pet has a microchip */
                microchipped?: boolean;
                /** @description Whether the pet has special medical needs */
                specialNeeds?: boolean;
                /** @description Additional medical notes */
                healthNotes?: string;
            };
        };
        /** @description Collection of pets with pagination */
        PetCollection: {
            data: components["schemas"]["Pet"][];
            pagination: {
                /** @description Current page number */
                page: number;
                /** @description Number of items per page */
                limit: number;
                /** @description Total number of items */
                totalItems: number;
                /** @description Total number of pages */
                totalPages: number;
            };
        };
        /** @description User account information */
        User: {
            /**
             * Format: uuid
             * @description Unique user identifier (UUID v7)
             * @example 019b4138-e0af-70b9-8f0c-6ea97d495dfa
             * @example 019b4128-6a6b-777c-9ae8-335e962c68d8
             */
            readonly id: string;
            /**
             * @description Unique username for login
             * @example johndoe
             * @example mysqluser
             */
            username: string;
            /**
             * Format: email
             * @description User email address
             * @example user@example.com
             * @example john.doe@petstore.com
             */
            email: string;
            /**
             * @description User's first name
             * @example John
             * @example Jane
             */
            firstName: string;
            /**
             * @description User's last name
             * @example Doe
             * @example Smith
             */
            lastName: string;
            /**
             * @description Phone number in E.164 format
             * @example +12025551234
             */
            phone?: string;
            /**
             * Format: date-time
             * @description Account creation timestamp (RFC 3339)
             * @example 2025-12-21T13:56:23Z
             * @example 2025-11-15T08:30:00Z
             */
            readonly createdAt: string;
            /**
             * Format: date-time
             * @description Account last update timestamp (RFC 3339)
             * @example 2025-12-21T13:56:23Z
             * @example 2025-12-21T15:30:45Z
             */
            readonly updatedAt: string;
            /**
             * Format: uuid
             * @description Optional tenant identifier for data isolation. When present, indicates this user belongs to a specific tenant. Null or omitted means the user is in the shared/public data pool.
             * @example 550e8400-e29b-41d4-a716-446655440000
             * @example 7c9e6679-7425-40de-944b-e07fc1f90ae7
             */
            readonly tenantId?: string | null;
            preferences?: {
                /** @description Whether to receive newsletter emails */
                newsletter?: boolean;
                /** @description Whether to receive notification emails */
                notifications?: boolean;
            };
        };
        /** @description Order payment information with polymorphic payment sources */
        OrderPayment: {
            /**
             * Format: uuid
             * @description Unique payment identifier
             * @example 2e3b4f5a-6b7c-8d9e-0f1a-2b3c4d5e6f7a
             */
            readonly id: string;
            /**
             * @description Payment amount (positive decimal)
             * @example 49.99
             * @example 100.50
             */
            amount: string;
            /**
             * @description Three-letter ISO 4217 currency code (uppercase)
             * @default USD
             * @enum {string}
             */
            currency: "USD" | "EUR" | "GBP" | "CAD" | "AUD";
            /** @description Payment source (card or bank account) */
            source: components["schemas"]["CardPaymentSource"] | components["schemas"]["BankAccountPaymentSource"];
            /**
             * @description Payment status
             * @enum {string}
             */
            readonly status: "PENDING" | "PROCESSING" | "SUCCEEDED" | "FAILED" | "CANCELLED";
            /**
             * Format: date-time
             * @description Payment creation timestamp
             */
            readonly createdAt?: string;
        };
        /**
         * Bank Card
         * @description Debit or credit card payment source
         */
        CardPaymentSource: {
            /**
             * @description Discriminator value for card payments (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "card";
            /**
             * @description Cardholder name
             * @example Jane Doe
             * @example John Smith
             */
            name: string;
            /**
             * @description Card number (masked when reading)
             * @example 4242424242424242
             * @example ************4242
             */
            number: string;
            /** @description Card security code */
            cvc?: string;
            /** @description Expiration month (1-12) */
            expMonth: number;
            /** @description Expiration year (4 digits) */
            expYear: number;
            /**
             * @description Card brand
             * @enum {string}
             */
            readonly brand?: "VISA" | "MASTERCARD" | "AMEX" | "DISCOVER" | "DINERS" | "JCB" | "UNIONPAY";
            /** @description Last 4 digits */
            readonly last4?: string;
            billingAddress?: {
                line1?: string;
                line2?: string;
                city?: string;
                state?: string;
                postalCode?: string;
                /** @description ISO 3166-1 alpha-2 country code */
                country?: string;
            };
        };
        /**
         * Bank Account
         * @description Bank account payment source
         */
        BankAccountPaymentSource: {
            /**
             * @description Discriminator value for bank account payments (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "bankAccount";
            /** @description Name of account holder */
            accountHolderName: string;
            /** @description Bank account number (masked when reading) */
            accountNumber: string;
            /** @description Bank routing number */
            routingNumber: string;
            /**
             * @description Type of bank account
             * @enum {string}
             */
            accountType: "CHECKING" | "SAVINGS";
            /** @description Name of the bank */
            readonly bankName?: string;
            /** @description Last 4 digits of account number */
            readonly last4?: string;
        };
        /** @description Pet category */
        Category: {
            /** @description Unique category identifier */
            id: string;
            /** @description Category name */
            name: string;
        };
        /** @description Hypermedia links for resource navigation */
        Links: {
            /**
             * Format: uri
             * @description Link to this resource
             */
            self: string;
        };
        /** @description Pet store order details */
        Order: {
            /**
             * Format: uuid
             * @description Unique order identifier (UUID v7)
             * @example 019b4139-1234-7abc-8def-123456789abc
             * @example 019b4127-5678-7def-9012-234567890def
             */
            readonly id: string;
            /**
             * Format: uuid
             * @description ID of the pet being ordered
             * @example 019b4132-70aa-764f-b315-e2803d882a24
             * @example 019b4127-54d5-76d9-b626-0d4c7bfce5b6
             */
            petId: string;
            /**
             * Format: uuid
             * @description ID of the user placing the order
             * @example 019b4138-e0af-70b9-8f0c-6ea97d495dfa
             * @example 019b4128-6a6b-777c-9ae8-335e962c68d8
             */
            userId: string;
            /**
             * @description Order status
             * @example PLACED
             * @example APPROVED
             * @enum {string}
             */
            status: "PLACED" | "APPROVED" | "SHIPPED" | "DELIVERED" | "CANCELLED";
            /**
             * @description Total order amount
             * @example 125.50
             * @example 75.00
             * @example 200.99
             */
            totalAmount: string;
            /**
             * @description Currency code for the order amount (ISO 4217)
             * @default USD
             * @example USD
             * @example EUR
             * @example GBP
             */
            currency: string;
            /**
             * Format: date-time
             * @description Order creation timestamp (RFC 3339)
             * @example 2025-12-21T13:56:23Z
             * @example 2025-11-15T08:30:00Z
             */
            readonly createdAt: string;
            /**
             * Format: date-time
             * @description Order last update timestamp (RFC 3339)
             * @example 2025-12-21T13:56:23Z
             * @example 2025-12-21T15:30:45Z
             */
            readonly updatedAt: string;
            /**
             * Format: uuid
             * @description Optional tenant identifier for data isolation. When present, indicates this order belongs to a specific tenant. Null or omitted means the order is in the shared/public data pool.
             * @example 550e8400-e29b-41d4-a716-446655440000
             * @example 7c9e6679-7425-40de-944b-e07fc1f90ae7
             */
            readonly tenantId?: string | null;
        };
        /** @description Generic API response */
        ApiResponse: {
            /** @description Human-readable message */
            message?: string;
            /** @description Whether the operation was successful */
            success?: boolean;
        };
        /** @description Tags associated with pets */
        Tag: {
            /** @description Unique tag identifier */
            id: string;
            /** @description Tag name */
            name: string;
        };
        /** @description RFC 9457 Problem Details for HTTP APIs */
        Error: {
            /**
             * Format: uri
             * @description A URI reference that identifies the problem type
             * @example https://petstoreapi.com/errors/not-found
             * @example https://petstoreapi.com/errors/validation-error
             */
            type: string;
            /**
             * @description A short, human-readable summary of the problem
             * @example Resource Not Found
             * @example Validation Error
             */
            title: string;
            /**
             * @description The HTTP status code
             * @example 404
             * @example 400
             * @example 422
             */
            status: number;
            /**
             * @description A human-readable explanation specific to this occurrence
             * @example The requested pet with ID '123' was not found
             */
            detail?: string;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence
             * @example /v1/pets/123
             */
            instance?: string;
            /** @description Detailed validation errors (for 422 responses) */
            errors?: {
                /** @description The field that failed validation */
                field: string;
                /** @description Description of the validation error */
                message: string;
                /** @description Machine-readable error code */
                code?: string;
            }[];
        };
    };
    responses: {
        /** @description Bad request - Invalid parameters */
        BadRequest: {
            headers: {
                "RateLimit-Limit": components["headers"]["RateLimit-Limit"];
                "RateLimit-Remaining": components["headers"]["RateLimit-Remaining"];
                "RateLimit-Reset": components["headers"]["RateLimit-Reset"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description Unauthorized - Authentication required */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description Forbidden - Insufficient permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests - Rate limit exceeded */
        TooManyRequests: {
            headers: {
                "RateLimit-Limit": components["headers"]["RateLimit-Limit"];
                /** @example 0 */
                "RateLimit-Remaining"?: number;
                "RateLimit-Reset": components["headers"]["RateLimit-Reset"];
                /**
                 * @description Number of seconds to wait before retrying
                 * @example 60
                 */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description Unprocessable entity - Validation errors */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description Method not allowed - HTTP method not supported for this endpoint */
        MethodNotAllowed: {
            headers: {
                /**
                 * @description List of HTTP methods that are allowed for this resource
                 * @example GET, POST, PUT, DELETE
                 */
                Allow?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Optional tenant identifier for data isolation. When provided, all operations will be scoped to this tenant, ensuring data separation between different organizations or users. If omitted, operations will access the shared/public data pool where data may be visible to and modified by other users. */
        TenantID: string;
    };
    requestBodies: never;
    headers: {
        /**
         * @description The maximum number of requests allowed in the current time window
         * @example 100
         */
        "RateLimit-Limit": number;
        /**
         * @description The number of requests remaining in the current time window
         * @example 95
         */
        "RateLimit-Remaining": number;
        /**
         * @description The time at which the current rate limit window resets (Unix timestamp)
         * @example 1702648800
         */
        "RateLimit-Reset": number;
    };
    pathItems: {
        "pet-resource": {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Unique identifier for the pet */
                    id: string;
                };
                cookie?: never;
            };
            /**
             * Get Pet Details
             * @description Retrieve detailed information about a specific pet
             */
            get: operations["getPetById"];
            /**
             * Update Pet
             * @description Update information for an existing pet
             */
            put: operations["updatePetById"];
            post?: never;
            /**
             * Delete Pet
             * @description Remove a pet from the system
             */
            delete: operations["deletePetById"];
            options?: never;
            head?: never;
            patch?: never;
            trace?: never;
        };
    };
}
export type $defs = Record<string, never>;
export interface operations {
    getPet: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional tenant identifier for data isolation. When provided, all operations will be scoped to this tenant, ensuring data separation between different organizations or users. If omitted, operations will access the shared/public data pool where data may be visible to and modified by other users. */
                "X-Tenant-ID"?: components["parameters"]["TenantID"];
            };
            path: {
                /**
                 * @description Unique identifier for the pet
                 * @example 01936c8f-1234-7000-8000-111111111111
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response with pet details */
            200: {
                headers: {
                    "RateLimit-Limit": components["headers"]["RateLimit-Limit"];
                    "RateLimit-Remaining": components["headers"]["RateLimit-Remaining"];
                    "RateLimit-Reset": components["headers"]["RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pet"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    updatePet: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional tenant identifier for data isolation. When provided, all operations will be scoped to this tenant, ensuring data separation between different organizations or users. If omitted, operations will access the shared/public data pool where data may be visible to and modified by other users. */
                "X-Tenant-ID"?: components["parameters"]["TenantID"];
            };
            path: {
                /**
                 * @description Unique identifier for the pet
                 * @example 01936c8f-1234-7000-8000-111111111111
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Max Updated",
                 *       "species": "DOG",
                 *       "breed": "Golden Retriever",
                 *       "ageMonths": 25,
                 *       "size": "LARGE",
                 *       "color": "Golden",
                 *       "gender": "MALE",
                 *       "goodWithKids": true,
                 *       "price": "275.00",
                 *       "currency": "USD",
                 *       "status": "AVAILABLE",
                 *       "description": "Friendly and well-trained golden retriever",
                 *       "medicalInfo": {
                 *         "vaccinated": true,
                 *         "spayedNeutered": true,
                 *         "microchipped": true,
                 *         "specialNeeds": false,
                 *         "healthNotes": "Up to date on all vaccinations, recent dental cleaning"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Pet"];
            };
        };
        responses: {
            /** @description Pet updated successfully */
            200: {
                headers: {
                    "RateLimit-Limit": components["headers"]["RateLimit-Limit"];
                    "RateLimit-Remaining": components["headers"]["RateLimit-Remaining"];
                    "RateLimit-Reset": components["headers"]["RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pet"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    deletePet: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional tenant identifier for data isolation. When provided, all operations will be scoped to this tenant, ensuring data separation between different organizations or users. If omitted, operations will access the shared/public data pool where data may be visible to and modified by other users. */
                "X-Tenant-ID"?: components["parameters"]["TenantID"];
            };
            path: {
                /**
                 * @description Unique identifier for the pet
                 * @example 01936c8f-1234-7000-8000-111111111111
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pet deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listPets: {
        parameters: {
            query?: {
                /** @description Filter by pet species */
                species?: "DOG" | "CAT" | "RABBIT" | "BIRD" | "REPTILE" | "OTHER";
                /** @description Filter by adoption status */
                status?: "AVAILABLE" | "PENDING" | "ADOPTED";
                /** @description Minimum age in months */
                ageMin?: number;
                /** @description Maximum age in months */
                ageMax?: number;
                /** @description Filter by pet size */
                size?: "SMALL" | "MEDIUM" | "LARGE";
                /** @description Filter pets that are good with children */
                goodWithKids?: boolean;
                /** @description Page number for pagination */
                page?: number;
                /** @description Number of items per page */
                limit?: number;
            };
            header?: {
                /** @description Optional tenant identifier for data isolation. When provided, all operations will be scoped to this tenant, ensuring data separation between different organizations or users. If omitted, operations will access the shared/public data pool where data may be visible to and modified by other users. */
                "X-Tenant-ID"?: components["parameters"]["TenantID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response with pet collection */
            200: {
                headers: {
                    "RateLimit-Limit": components["headers"]["RateLimit-Limit"];
                    "RateLimit-Remaining": components["headers"]["RateLimit-Remaining"];
                    "RateLimit-Reset": components["headers"]["RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PetCollection"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    createPet: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional tenant identifier for data isolation. When provided, all operations will be scoped to this tenant, ensuring data separation between different organizations or users. If omitted, operations will access the shared/public data pool where data may be visible to and modified by other users. */
                "X-Tenant-ID"?: components["parameters"]["TenantID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Max",
                 *       "species": "DOG",
                 *       "breed": "Golden Retriever",
                 *       "ageMonths": 24,
                 *       "size": "LARGE",
                 *       "color": "Golden",
                 *       "gender": "MALE",
                 *       "goodWithKids": true,
                 *       "price": "250.00",
                 *       "currency": "USD",
                 *       "status": "AVAILABLE",
                 *       "description": "Friendly golden retriever looking for an active family",
                 *       "medicalInfo": {
                 *         "vaccinated": true,
                 *         "spayedNeutered": true,
                 *         "microchipped": true,
                 *         "specialNeeds": false,
                 *         "healthNotes": "Up to date on all vaccinations"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Pet"];
            };
        };
        responses: {
            /** @description Pet created successfully */
            201: {
                headers: {
                    "RateLimit-Limit": components["headers"]["RateLimit-Limit"];
                    "RateLimit-Remaining": components["headers"]["RateLimit-Remaining"];
                    "RateLimit-Reset": components["headers"]["RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pet"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    createChatCompletion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description A list of messages comprising the conversation so far */
                    messages: {
                        /**
                         * @description The role of the message author
                         * @enum {string}
                         */
                        role: "SYSTEM" | "USER" | "ASSISTANT";
                        /** @description The contents of the message */
                        content: string;
                    }[];
                    /**
                     * @description ID of the model to use
                     * @default PET_ADVISOR_1
                     * @enum {string}
                     */
                    model?: "PET_ADVISOR_1" | "PET_ADVISOR_TURBO";
                    /**
                     * @description If true, partial message deltas will be sent via Server-Sent Events
                     * @default true
                     */
                    stream?: boolean;
                    /**
                     * @description Maximum number of tokens to generate
                     * @default 1024
                     */
                    maxTokens?: number;
                    /**
                     * @description Sampling temperature between 0 and 2
                     * @default 1
                     */
                    temperature?: number;
                };
            };
        };
        responses: {
            /** @description Successful response. Format depends on the `stream` parameter. */
            201: {
                headers: {
                    /** @description Response content type */
                    "Content-Type"?: "text/event-stream" | "application/json";
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                    "application/json": {
                        /** @description Unique identifier for the completion */
                        id?: string;
                        /** @constant */
                        object?: "chat.completion";
                        /** @description Unix timestamp of when the completion was created */
                        created?: number;
                        /** @description Model used for completion */
                        model?: string;
                        choices?: {
                            index?: number;
                            message?: {
                                /** @constant */
                                role?: "assistant";
                                content?: string;
                            };
                            /** @enum {string} */
                            finishReason?: "STOP" | "LENGTH" | "CONTENT_FILTER";
                        }[];
                        usage?: {
                            promptTokens?: number;
                            completionTokens?: number;
                            totalTokens?: number;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    uploadPetPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique identifier for the pet
                 * @example 01936c8f-1234-7000-8000-111111111111
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /**
                     * @description Additional data to pass to server
                     * @example
                     */
                    additionalMetadata?: string;
                    /**
                     * Format: binary
                     * @description File to upload
                     * @example
                     */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description Operation successful */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": 3,
                     *       "type": "ex dolor",
                     *       "message": "Pecus carcer cometes credo."
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createOrderPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique identifier for the order
                 * @example 019b4139-1234-7abc-8def-123456789abc
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderPayment"];
            };
        };
        responses: {
            /** @description Payment successful */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPayment"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getInventory: {
        parameters: {
            query?: {
                /**
                 * @description Values to filter inventory status (comma-separated).
                 * @example [
                 *       "AVAILABLE",
                 *       "PENDING"
                 *     ]
                 */
                status?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operation successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional tenant identifier for data isolation. When provided, all operations will be scoped to this tenant, ensuring data separation between different organizations or users. If omitted, operations will access the shared/public data pool where data may be visible to and modified by other users. */
                "X-Tenant-ID"?: components["parameters"]["TenantID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                /**
                 * @example {
                 *       "petId": "019b4132-70aa-764f-b315-e2803d882a24",
                 *       "userId": "019b4138-e0af-70b9-8f0c-6ea97d495dfa"
                 *     }
                 */
                "application/json": components["schemas"]["Order"];
            };
        };
        responses: {
            /** @description Operation successful */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 44524671,
                     *       "petId": 90180021,
                     *       "quantity": 23,
                     *       "shipDate": "2025-08-15",
                     *       "status": "placed",
                     *       "complete": false
                     *     }
                     */
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional tenant identifier for data isolation. When provided, all operations will be scoped to this tenant, ensuring data separation between different organizations or users. If omitted, operations will access the shared/public data pool where data may be visible to and modified by other users. */
                "X-Tenant-ID"?: components["parameters"]["TenantID"];
            };
            path: {
                /**
                 * @description Unique identifier for the order
                 * @example 019b4139-1234-7abc-8def-123456789abc
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operation successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 40238436,
                     *       "petId": 69923630,
                     *       "quantity": 87,
                     *       "shipDate": "2024-12-09",
                     *       "status": "approved",
                     *       "complete": false
                     *     }
                     */
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    callbackOrder: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional tenant identifier for data isolation. When provided, all operations will be scoped to this tenant, ensuring data separation between different organizations or users. If omitted, operations will access the shared/public data pool where data may be visible to and modified by other users. */
                "X-Tenant-ID"?: components["parameters"]["TenantID"];
            };
            path: {
                /**
                 * @description Unique identifier for the order
                 * @example 019b4139-1234-7abc-8def-123456789abc
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                /**
                 * @example {
                 *       "amount": "738.05",
                 *       "currency": "USD",
                 *       "timestamp": "1758613403",
                 *       "callbackUrl": "https://example.com/callbacks/orders/1312312"
                 *     }
                 */
                "application/json": {
                    /** @description The payment amount */
                    amount: string;
                    /** @description The payment currency */
                    currency: string;
                    /** @description Operation timestamp */
                    timestamp: string;
                    /**
                     * Format: uri
                     * @description URL to call back when processing is complete
                     */
                    callbackUrl: string;
                };
            };
        };
        responses: {
            /** @description Callback enqueued successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteOrder: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional tenant identifier for data isolation. When provided, all operations will be scoped to this tenant, ensuring data separation between different organizations or users. If omitted, operations will access the shared/public data pool where data may be visible to and modified by other users. */
                "X-Tenant-ID"?: components["parameters"]["TenantID"];
            };
            path: {
                /**
                 * @description Unique identifier for the order
                 * @example 019b4139-1234-7abc-8def-123456789abc
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional tenant identifier for data isolation. When provided, all operations will be scoped to this tenant, ensuring data separation between different organizations or users. If omitted, operations will access the shared/public data pool where data may be visible to and modified by other users. */
                "X-Tenant-ID"?: components["parameters"]["TenantID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                /**
                 * @example {
                 *       "username": "kylekinh",
                 *       "firstName": "Kyle",
                 *       "lastName": "Kihn",
                 *       "email": "kyle.kihn@example.com",
                 *       "password": "SecurePass123!",
                 *       "phone": "+18638982053"
                 *     }
                 */
                "application/json": components["schemas"]["User"];
            };
        };
        responses: {
            /** @description User created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getUserById: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional tenant identifier for data isolation. When provided, all operations will be scoped to this tenant, ensuring data separation between different organizations or users. If omitted, operations will access the shared/public data pool where data may be visible to and modified by other users. */
                "X-Tenant-ID"?: components["parameters"]["TenantID"];
            };
            path: {
                /**
                 * @description Unique identifier for the user
                 * @example user_abc123xyz
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operation successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "019b4138-e0af-70b9-8f0c-6ea97d495dfa",
                     *       "username": "ameliehackett",
                     *       "firstName": "Amelie",
                     *       "lastName": "Hackett",
                     *       "email": "amelie.hackett@example.com",
                     *       "phone": "+16324377270",
                     *       "createdAt": "2025-12-21T13:56:23Z",
                     *       "updatedAt": "2025-12-21T13:56:23Z"
                     *     }
                     */
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional tenant identifier for data isolation. When provided, all operations will be scoped to this tenant, ensuring data separation between different organizations or users. If omitted, operations will access the shared/public data pool where data may be visible to and modified by other users. */
                "X-Tenant-ID"?: components["parameters"]["TenantID"];
            };
            path: {
                /**
                 * @description Unique identifier for the user
                 * @example user_abc123xyz
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                /**
                 * @example {
                 *       "firstName": "Jeffrey",
                 *       "lastName": "Kris",
                 *       "email": "jeffrey.kris@example.com",
                 *       "phone": "+18634063542"
                 *     }
                 */
                "application/json": components["schemas"]["User"];
            };
        };
        responses: {
            /** @description User updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional tenant identifier for data isolation. When provided, all operations will be scoped to this tenant, ensuring data separation between different organizations or users. If omitted, operations will access the shared/public data pool where data may be visible to and modified by other users. */
                "X-Tenant-ID"?: components["parameters"]["TenantID"];
            };
            path: {
                /**
                 * @description Unique identifier for the user
                 * @example user_abc123xyz
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    createToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "username": "kylekinh",
                 *       "password": "SecurePass123!"
                 *     }
                 */
                "application/json": {
                    /**
                     * @description Login username
                     * @example johndoe
                     */
                    username: string;
                    /**
                     * @description User password (never returned in responses)
                     * @example securePassword123
                     */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    "RateLimit-Limit": components["headers"]["RateLimit-Limit"];
                    "RateLimit-Remaining": components["headers"]["RateLimit-Remaining"];
                    "RateLimit-Reset": components["headers"]["RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Authentication token */
                        token?: string;
                        /**
                         * Format: date-time
                         * @description Token expiration time
                         */
                        expiresAt?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    orderStatusChangedWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description Unique identifier for this webhook event
                     * @example evt_9f4a8b3c-2d5e-6f7g-8h9i-0j1k2l3m4n5o
                     */
                    eventId: string;
                    /**
                     * @description Type of event
                     * @constant
                     */
                    eventType: "order.statusChanged";
                    /**
                     * Format: date-time
                     * @description When the event occurred (RFC 3339)
                     */
                    timestamp: string;
                    data: {
                        order: components["schemas"]["Order"];
                        /**
                         * @description The order status before this change
                         * @enum {string}
                         */
                        previousStatus: "PLACED" | "APPROVED" | "SHIPPED" | "DELIVERED" | "CANCELLED";
                        /**
                         * @description The new order status after this change
                         * @enum {string}
                         */
                        newStatus: "PLACED" | "APPROVED" | "SHIPPED" | "DELIVERED" | "CANCELLED";
                        /**
                         * Format: date-time
                         * @description When the status change occurred
                         */
                        changedAt?: string;
                        /** @description Identifier of who/what triggered the change (user ID or system) */
                        changedBy?: string;
                    };
                };
            };
        };
        responses: {
            /** @description Webhook received successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid webhook signature */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    paymentSucceededWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description Unique identifier for this webhook event
                     * @example evt_3c4d5e6f-7g8h-9i0j-1k2l-3m4n5o6p7q8r
                     */
                    eventId: string;
                    /**
                     * @description Type of event
                     * @constant
                     */
                    eventType: "payment.succeeded";
                    /**
                     * Format: date-time
                     * @description When the event occurred (RFC 3339)
                     */
                    timestamp: string;
                    data: {
                        payment: components["schemas"]["OrderPayment"];
                        order: components["schemas"]["Order"];
                        /** @description Payment receipt information */
                        receipt?: {
                            /**
                             * Format: uuid
                             * @description Unique receipt identifier
                             */
                            receiptId?: string;
                            /**
                             * Format: uri
                             * @description URL to download the receipt
                             */
                            receiptUrl?: string;
                            /**
                             * Format: date-time
                             * @description When the receipt was generated
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
        };
        responses: {
            /** @description Webhook received successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid webhook signature */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPetById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier for the pet */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pet found */
            200: {
                headers: {
                    "RateLimit-Limit": components["headers"]["RateLimit-Limit"];
                    "RateLimit-Remaining": components["headers"]["RateLimit-Remaining"];
                    "RateLimit-Reset": components["headers"]["RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pet"];
                };
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    updatePetById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier for the pet */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Pet"];
            };
        };
        responses: {
            /** @description Pet updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pet"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deletePetById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier for the pet */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pet deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
